export { default as Header } from './Header'
export { default as Paragraph } from './Paragraph'
export { default as ParagraphHeader } from './ParagraphHeader'
export { default as RegisterForm } from './RegisterForm'
export { default as FindUs } from './FindUs'
export { default as ContactUs } from './ContactUs'
export { default as Footer } from './Footer'
export { default as Events } from './Events'
